baseURL = '/'
languageCode = 'en-us'
title = 'Omniroo'
theme = 'hugo-saasify-theme'

# Required Features
pygmentsCodeFences = true  # Enable syntax highlighting
pygmentsUseClasses = true
enableEmoji = true        # Enable emoji support
enableGitInfo = true      # Enable Git info for lastmod

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true      # Required for TailwindCSS

[params]
  description = "Make data sync simple"
  author = "Omniroo"
  logo = "/images/logo.svg"

  # Header Logo
  [params.header.logo]
    src = "/images/logo.svg"
  
  # Global CTA Configuration
  [params.cta]
    enable = true
    title = "Power Your Growth with Data Syncing"
    description = "Streamline subscriptions, prevent revenue loss, and scale with Stripe-HubSpot integration."
    gradient_from = "#7c3aed"  # Indigo-600
    gradient_to = "#1a365d"    # Purple-600
    gradient_angle = 160
    [params.cta.primary_button]
      text = "Get Started Free"
      url = "/get-started"
    [params.cta.secondary_button]
      text = "Book Demo"
      url = "/demo"



[menu]
  [[menu.main]]
    name = "Features"
    url = "/features"
    weight = 1
  [[menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 2
  [[menu.main]]
    name = "Company"
    url = "/company"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4
