baseURL = '/'
languageCode = 'en-us'
title = 'Omniroo'
theme = 'hugo-saasify-theme'

# Required Features
pygmentsCodeFences = true  # Enable syntax highlighting
pygmentsUseClasses = true
enableEmoji = true        # Enable emoji support
enableGitInfo = true      # Enable Git info for lastmod

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true      # Required for TailwindCSS

[params]
  description = "Make data sync simple"
  author = "Omniroo"
  logo = "/images/logo.svg"

  # Header Logo
  [params.header.logo]
    src = "/images/logo.svg"
  
  # Footer
  footerTitle = "Ready to get started?"
  footerDescription = "Get in touch or create an account."
  footerCopyrightText = "© 2024 Omniroo. All rights reserved."

  # Call to action
  ctaTitle = "Ready to dive in?"
  ctaDescription = "Start your free trial today."
  ctaButtonText = "Get started"
  ctaButtonUrl = "#"

  # Social links
  twitter = "#"
  github = "#"
  linkedin = "#"

[menu]
  [[menu.main]]
    name = "Features"
    url = "/features"
    weight = 1
  [[menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 2
  [[menu.main]]
    name = "Company"
    url = "/company"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4
