baseURL = 'https://omniroo.com/'
languageCode = 'en-us'
title = 'Omniroo'
theme = 'hugo-saasify-theme'

# Required Features
pygmentsCodeFences = true  # Enable syntax highlighting
pygmentsUseClasses = true
enableEmoji = true        # Enable emoji support
enableGitInfo = true      # Enable Git info for lastmod

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true      # Required for TailwindCSS

[params]
  description = "Make data sync simple"
  author = "Omniroo"
  logo = "/images/logo.svg"
  googleTagManager = "GTM-T4T7S8MR"

  # Header Logo
  [params.header.logo]
    src = "/images/logo.svg"

  # Button configuration
  [params.header.buttons]
    # Sign In button
    [params.header.buttons.signIn]
      text = "Sign in"
      url = "https://app.omniroo.com/"
    
    # Get Started button
    [params.header.buttons.getStarted]
      text = "Get Started"
      url = "https://app.omniroo.com/signup"
  
  # Global CTA Configuration
  [params.cta]
    enable = true
    title = "Power Your Growth with Data Syncing"
    description = "Streamline subscriptions, prevent revenue loss, and scale with Stripe-HubSpot integration."
    gradient_from = "#7c3aed"  # Indigo-600
    gradient_to = "#1a365d"    # Purple-600
    gradient_angle = 160
    [params.cta.primary_button]
      text = "Get Started for Free"
      url = "https://app.omniroo.com/signup"

  # Blog configuration
  [params.blog]
    enable = true
    title = "Latest Articles"
    subtitle = "Learn more about SaaS CRM and automation"

    # Blog CTA configuration
    [params.blog.cta]
      enable = true  # Enable/disable CTA in blog posts

    # Sidebar configuration
    [params.blog.sidebar]
      # Recent articles section
      [params.blog.sidebar.recent]
        enable = true
        title = "Recent Articles"
        count = 5
      
      # Categories section
      [params.blog.sidebar.categories]
        enable = true
        title = "Categories"
      
      # Tags section
      [params.blog.sidebar.tags]
        enable = true
        title = "Popular Tags"
        count = 20

[menu]
  [[menu.main]]
    name = "How it Works"
    url = "/how_it_works"
    weight = 1
  [[menu.main]]
    name = "Docs"
    url = "/docs/get-started"
    weight = 2
  [[menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 4

[params.docs]
  enable = true
  title = "Documentation"
  description = "Omniroo Documentation"
  sidebar = true
  versioning = true
  search = true

[[redirects]]
  from = "/docs"
  to = "/docs/get-started"
  status = 301

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
  docs = ["HTML"]

[params.footer]
  column_1_title = "Product"
  column_2_title = "Learn"
  column_3_title = "Legal"

  # Footer Column 1 Menu
  [[menu.footer_column_1]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.footer_column_1]]
    name = "How it Works"
    url = "/how_it_works/"
    weight = 2
  [[menu.footer_column_1]]
    name = "Pricing"
    url = "/pricing/"
    weight = 3

  # Footer Column 2 Menu
  [[menu.footer_column_2]]
    name = "Docs"
    url = "/docs/get-started"
    weight = 1
  [[menu.footer_column_2]]
    name = "Blog"
    url = "/blog"
    weight = 2
  [[menu.footer_column_2]]
    name = "Contact Us"
    url = "/contact"
    weight = 3

  # Footer Column 3 Menu
  [[menu.footer_column_3]]
    name = "Privacy Policy"
    url = "/privacy"
    weight = 1
  [[menu.footer_column_3]]
    name = "Terms of Service"
    url = "/terms"
    weight = 2
  [[menu.footer_column_3]]
    name = "Security"
    url = "/Security"
    weight = 3
